server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/read?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456789a
    hikari:
      connection-init-sql: SET NAMES utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    restart:
      exclude: application.yml
  profiles:
    active: dev